name: Test Streamlit Simulation App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-streamlit-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check Streamlit App Syntax
        run: |
          python -m py_compile completed-streamlit-simulation.py

      - name: Optional: Run Streamlit headlessly (dry test)
        run: |
          streamlit run completed-streamlit-simulation.py --server.headless true &
          sleep 10
          pkill streamlit
